services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3.11"
    volumes:
      - ..:/workspace:cached
      - dispatch-node-modules:/workspace/src/dispatch/static/dispatch/node_modules
    command: sleep infinity
    environment:
      - NODE_ENV=development
      - STATIC_DIR=/static
      - LOG_LEVEL=DEBUG
      - DATABASE_URL=postgresql://dispatch:dispatch@db:5432/dispatch
      - REDIS_URL=redis://redis:6379
      - SESSION_SECRET=dev-session-secret
      - DISPATCH_ENCRYPTION_KEY=NJHDWDJ3PbHT8h
      - DISPATCH_JWT_SECRET=foo
      - DATABASE_HOSTNAME=db
      - DATABASE_CREDENTIALS=dispatch:dispatch
      - ROLLUP_SKIP_NATIVES=true
      - npm_config_arch=arm64
      - npm_config_platform=darwin
    ports:
      - "8000:8000"
      - "8080:8080"

  db:
    image: postgres:15-alpine
    platform: linux/arm64
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dispatch
      - POSTGRES_PASSWORD=dispatch
      - POSTGRES_DB=dispatch
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    platform: linux/arm64
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  postgres-data:
  redis-data:
  dispatch-node-modules:
